name: "Setup Erlang Build Environment"
description: "Setups the build environment for Helium Erlang nodes"

inputs:
  otp-version:
    description: “The OTP version for Erlang”
    required: true
  rebar3-version:
    description: “The rebar3 version”
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Install Erlang OTP ${{ inputs.otp-version }} / rebar3 ${{ inputs.rebar3-version }}
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ inputs.otp-version }}
        rebar3-version: ${{ inputs.rebar3-version }}
        
    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        
    - name: Install Dependencies
      run: |
        sudo apt-get install -y libsodium-dev liblz4-dev
        
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.12